<a href="https://colab.research.google.com/github/rodrigorissettoterra/Python_estudos/blob/main/03_Pandas_I_O_trabalhando_com_diferentes_formatos_de_arquivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Este projeto consiste em aprimorar a técnica de manipulação de diferentes tipos de arquivos, tanto na entrada de uma base dados, quanto na saída.

Importando bibliotecas necessárias

In [1]:
import pandas as pd

#Arquivo do tipo .CSV

##Baixar a base de dados em .CSV

Baixando a base de dados a ser utilizada e salvando-a em uma variável para ser utilizada posteriormente

In [2]:
df_csv = pd.read_csv('https://raw.githubusercontent.com/rodrigorissettoterra/Python_estudos/main/superstore_data.csv', encoding='ISO-8859-1')
df_csv

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

##Salvar a base de dados utilizada em formato .CSV

In [3]:
arquivo_em_csv = df_csv.to_csv('nome_do_arquivo_em_csv.csv', sep=",", index=False)
arquivo_em_csv

Arquivo gerado com sucesso:

![image.png]()

verificando o arquivo criado

In [4]:
pd.read_csv('/content/nome_do_arquivo_em_csv.csv')

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

#Arquivo em formato .XLSX

##Baixar a base de dados em .XLSX

In [5]:
df_excel = pd.read_excel('https://github.com/rodrigorissettoterra/Python_estudos/blob/main/emissoes_CO2.xlsx?raw=True')
df_excel

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

Verificando se existem outras planilhas dentro da base de dados

In [6]:
pd.ExcelFile('https://github.com/rodrigorissettoterra/Python_estudos/blob/main/emissoes_CO2.xlsx?raw=True').sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

Podemos ver que o arquivo baixado possui 3 abas de planilhas

Visualizando a planilha 2

In [7]:
planilha2 = pd.read_excel('https://github.com/rodrigorissettoterra/Python_estudos/blob/main/emissoes_CO2.xlsx?raw=True',
                          sheet_name='emissoes_percapita')
planilha2

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

Visualizando a planilha 3

In [8]:
planilha3 = pd.read_excel('https://github.com/rodrigorissettoterra/Python_estudos/blob/main/emissoes_CO2.xlsx?raw=True',
                          sheet_name='fontes')
planilha3

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

##Salvar a base de dados utilizada em formato .XLSX

Apenas para exercícios, salvarei a planilha número 2

In [9]:
planilha2.to_excel('nome_do_arquivo_em_xlsx.xlsx', index=False)

Arquivo criado com sucesso:

![image.png]()

Verificando se a criação do arquivo não teve problemas com a conversão

In [10]:
pd.read_excel('/content/nome_do_arquivo_em_xlsx.xlsx')

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

#Arquivo em formato .JSON

##Baixar base de dados em formato .JSON

In [11]:
df_json = pd.read_json('https://raw.githubusercontent.com/rodrigorissettoterra/Python_estudos/main/pacientes.json')
df_json

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

Normalizando a coluna "Pacientes"

In [12]:
df_json_norm = pd.json_normalize(df_json['Pacientes'])
df_json_norm

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

##Salvar a base de dados utilizada em formato .JSON

In [13]:
df_json_norm.to_json('nome_do_arquivo_em_json.json')

Arquivo criado com sucesso:

![image.png]()

Verificando alguma inconsistência na conversão dos dados

In [14]:
pd.read_json('/content/nome_do_arquivo_em_json.json')

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,1,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,2,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,3,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

#Arquivo em formato .HTML

##Baixar base de dados em formato .HTML

In [15]:
df_html = pd.read_html('https://en.wikipedia.org/wiki/AFI%27s_100_Years...100_Movies')
df_html

[                                                    0  \
 0                                                1998
 1                                                1999
 2                                                2000
 3                                                2001
 4                                                2002
 5                                                2003
 6                                                2004
 7                                                2005
 8                                                2005
 9                                                2006
 10                                               2006
 11                                               2007
 12                                               2008
 13  .mw-parser-output .hlist dl,.mw-parser-output ...

                                                     1
 0                                          100 Movies
 1                                           100 Stars
 2                                          100 Laughs
 3                                         100 Thrills
 4                                        100 Passions
 5                               100 Heroes & Villains
 6                                           100 Songs
 7                                    100 Movie Quotes
 8                                           25 Scores
 9                                          100 Cheers
 10                                        25 Musicals
 11                               100 Movies (Updated)
 12                                    AFI's 10 Top 10
 13  .mw-parser-output .hlist dl,.mw-parser-output ...  ,
                       Film  Release year              Director  \
 0             Citizen Kane          1941          Orson Welles
 1               Casablanca          1942        Michael Curtiz
 2            The Godfather          1972  Francis Ford Coppola
 3       Gone with the Wind          1939        Victor Fleming
 4       Lawrence of Arabia          1962            David Lean
 ..                     ...           ...                   ...
 118        Sophie's Choice          1982        Alan J. Pakula
 119  The Last Picture Show          1971     Peter Bogdanovich
 120     Do the Right Thing          1989             Spike Lee
 121           Blade Runner          1982          Ridley Scott
 122              Toy Story          1995         John Lasseter

                               Production companies 1998 Rank 2007 Rank
 0                               RKO Radio Pictures         1         1
 1                            Warner Bros. Pictures         2         3
 2           Paramount Pictures, Alfran Productions         3         2
 3                  Selznick International Pictures         4         6
 4                                 Horizon Pictures         5         7
 ..                                             ...       ...       ...
 118                              ITC Entertainment         -        91
 119                                BBS Productions         -        95
 120                  40 Acres and a Mule Filmworks         -        96
 121                The Ladd Company, Shaw Brothers         -        97
 122  Walt Disney Pictures, Pixar Animation Studios         -        99

 [123 rows x 6 columns]]

Selecionando a tabela de maior interesse

In [16]:
top_100_filmes = df_html[1]
top_100_filmes

,Film,Release year,Director,Production companies,1998 Rank,2007 Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2,3
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3,2
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4,6
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5,7
...,...,...,...,...,...,...
118,Sophie's Choice,1982,Alan J. Pakula,ITC Entertainment,-,91
119,The Last Picture Show,1971,Peter Bogdanovich,BBS Productions,-,95
120,Do the Right Thing,1989,Spike Lee,40 Acres and a Mule Filmworks,-,96
121,Blade Runner,1982,Ridley Scott,"The Ladd Company, Shaw Brothers",-,97
122,Toy Story,1995,John Lasseter,"Walt Disney Pictures, Pixar Animation Studios",-,99

##Salvar a base de dados utilizada em formato .HTML

In [17]:
top_100_filmes.to_html('nome_do_arquivo_em_html.html')

Arquivo criado com sucesso:

![image.png]()

Verificando possíveis erros de conversão

In [18]:
df_html_teste = pd.read_html('/content/nome_do_arquivo_em_html.html')
df_html_teste

[     Unnamed: 0                   Film  Release year              Director  \
 0             0           Citizen Kane          1941          Orson Welles
 1             1             Casablanca          1942        Michael Curtiz
 2             2          The Godfather          1972  Francis Ford Coppola
 3             3     Gone with the Wind          1939        Victor Fleming
 4             4     Lawrence of Arabia          1962            David Lean
 ..          ...                    ...           ...                   ...
 118         118        Sophie's Choice          1982        Alan J. Pakula
 119         119  The Last Picture Show          1971     Peter Bogdanovich
 120         120     Do the Right Thing          1989             Spike Lee
 121         121           Blade Runner          1982          Ridley Scott
 122         122              Toy Story          1995         John Lasseter

                               Production companies 1998 Rank 2007 Rank
 0                               RKO Radio Pictures         1         1
 1                            Warner Bros. Pictures         2         3
 2           Paramount Pictures, Alfran Productions         3         2
 3                  Selznick International Pictures         4         6
 4                                 Horizon Pictures         5         7
 ..                                             ...       ...       ...
 118                              ITC Entertainment         -        91
 119                                BBS Productions         -        95
 120                  40 Acres and a Mule Filmworks         -        96
 121                The Ladd Company, Shaw Brothers         -        97
 122  Walt Disney Pictures, Pixar Animation Studios         -        99

 [123 rows x 7 columns]]

#Arquivo em formato .XML

##Baixar base de dados em formato .XML

In [19]:
df_xml = pd.read_xml('https://raw.githubusercontent.com/rodrigorissettoterra/Python_estudos/main/imdb_top_1000.xml')
df_xml

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,None
996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,None
997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,None,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,None
999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,None,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,None

##Salvar a base de dados utilizada em formato .XML

In [20]:
df_xml.to_xml('nome_do_arquivo_em_xml.xml')

A criação do arquivo ocorreu com sucesso:

![image.png]()

Verificando se ocorreu algum problema na conversão dos dados

In [21]:
pd.read_xml('/content/nome_do_arquivo_em_xml.xml')

,level_0,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,None
996,996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,None
997,997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,None,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,None
999,999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,None,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,None

#Base de dados baixados diretamente de banco de dados

Biliotecas necessárias

In [22]:
from sqlalchemy import create_engine, MetaData, Table, inspect

In [23]:
pip install --upgrade 'sqlalchemy<2.0'

Requirement already satisfied: sqlalchemy<2.0 in /usr/local/lib/python3.10/dist-packages (1.4.51)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.0) (3.0.2)

Criação do banco de dados

In [24]:
engine = create_engine('sqlite:///:memory')

Escrever dados no banco de dados

In [25]:
url = '/content/drive/MyDrive/Base de dados/clientes_banco.csv'

In [26]:
dados = pd.read_csv(url)
dados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
dados.to_sql('clientes', engine, index=False)

Inspecionar o banco de dados

In [28]:
inspector = inspect(engine)

Verificando se conseguimos criar a tabela necessária "clientes"

In [29]:
print(inspector.get_table_names())

['clientes']

Consultas

In [30]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'

In [31]:
empregados = pd.read_sql(query, engine)

In [32]:
empregados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2.0,Empregado,Outro,12.0,427500.0,1.0,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2.0,Empregado,Outro,12.0,427500.0,1.0,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2.0,Empregado,Segurança,3.0,112500.0,1.0,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2.0,Empregado,Contabilidade,2.0,270000.0,1.0,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2.0,Empregado,Contabilidade,2.0,270000.0,1.0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
42918,5343739,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42919,5343740,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42920,5343741,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42921,5343742,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42922,5343743,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio

##Salvando a base de dados no SQL

In [33]:
empregados.to_sql('empregado', con=engine, index=False)

42923

Lendo uma tabela

In [35]:
pd.read_sql('empregado', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2.0,Empregado,Outro,12.0,427500.0,1.0,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2.0,Empregado,Outro,12.0,427500.0,1.0,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2.0,Empregado,Segurança,3.0,112500.0,1.0,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2.0,Empregado,Contabilidade,2.0,270000.0,1.0,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2.0,Empregado,Contabilidade,2.0,270000.0,1.0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
42918,5343739,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42919,5343740,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42920,5343741,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42921,5343742,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42922,5343743,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio

Leitura de apenas algumas colunas

In [37]:
pd.read_sql('empregado', engine, columns=['ID_Cliente', 'Grau_escolaridade',	'Rendimento_anual'])

       ID_Cliente           Grau_escolaridade  Rendimento_anual
0         5008804             Ensino superior          427500.0
1         5008805             Ensino superior          427500.0
2         5008806                Ensino médio          112500.0
3         5008815             Ensino superior          270000.0
4         5112956             Ensino superior          270000.0
...           ...                         ...               ...
42918     5343739  Ensino superior incompleto          450000.0
42919     5343740  Ensino superior incompleto          450000.0
42920     5343741  Ensino superior incompleto          450000.0
42921     5343742  Ensino superior incompleto          450000.0
42922     5343743  Ensino superior incompleto          450000.0

[42923 rows x 3 columns]

Excluindo dados do banco de dados

In [38]:
query2 = 'SELECT * FROM clientes'
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2.0,Empregado,Outro,12.0,427500.0,1.0,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2.0,Empregado,Outro,12.0,427500.0,1.0,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2.0,Empregado,Segurança,3.0,112500.0,1.0,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2.0,Empregado,Contabilidade,2.0,270000.0,1.0,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2.0,Empregado,Contabilidade,2.0,270000.0,1.0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
42918,5343739,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42919,5343740,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42920,5343741,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42921,5343742,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio
42922,5343743,41,Ensino superior incompleto,Casado,2.0,Empregado,Gerência,7.0,450000.0,0.0,Casa/apartamento próprio

In [40]:
query_delete = 'DELETE FROM clientes WHERE ID_Cliente=5008804'
with engine.connect() as conn:
  conn.execute(query_delete)

Verificando se a operação funcionou

In [41]:
query_verificacao = 'SELECT * FROM clientes WHERE ID_Cliente = 5008804'
pd.read_sql(query_verificacao, engine)

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

Exclusão do registro realizada com sucesso

Atualizando registros existentes

In [42]:
query_update = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
with engine.connect() as conn:
  conn.execute(query_update)

Verificando se a atualização foi realizada

Lembrando que, anteriormente:

![image.png]()

O cliente de ID 5008808 tinha o grau de escolaridade classificado como Ensino médio.

In [44]:
query_verificacao2 = 'SELECT * FROM clientes WHERE ID_Cliente = 5008808'
pd.read_sql(query_verificacao2, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008808,52,Ensino superior,Solteiro,1.0,Associado comercial,Vendas,8.0,270000.0,0.0,Casa/apartamento próprio